### ISSUE TITLE
Home page: Queries for country-level M&E metrics

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#542] opened 2018-08-07 22:22 UTC
This ticket describes queries we'll need at the top of the redesigned TolaActivity home page. They will be displayed using some combination of text and (hopefully) graphics, like so:

![image](https://user-images.githubusercontent.com/33670923/48164903-cc94a480-e298-11e8-8036-0a4700110701.png)

## Section title and subtitle
- [x] 1. The working title of the section is "Monitoring and Evaluation Status"
- [x] 2. The working subtitle is, "Are programs trackable and backed up with evidence?"

## Query 1: Programs have targets defined for all indicators
- [x] 1. For each program in the country portfolio: Do ALL of its indicators have targets defined? To meet the criteria, an indicator needs to:
- [x] 1.1. Have a target frequency selected.
- [x] 1.2. Have target values completed for all periods.
- [x] 1.2.1. In the case of LoP only target frequency, the LoP field must have a saved value.
- [x] 2. Across ALL programs in the country portfolio, what percentage of programs meet the criteria of having targets defined for ALL of their indicators?

## Query 2: Indicators have reported results
- [x] Across ALL indicators across ALL programs in the country portfolio: What percentage of indicators has at least one reported result?

## Query 3: Reported results are backed up with evidence
- [ ] Across ALL reported results associated with ALL indicators associated with ALL programs in the country portfolio: What percentage of results have either a document or TolaTable associated with it?

## Housekeeping
- [ ] Unit test/s written
- [ ] i18n tags included wherever applicable

**Comment by hannalcamp** [comment] 2018-12-04 22:56
Seeing a consistent issue with the country-level metric for "all programs have targets defined". Tolaland, as a country, only has 6 programs out of 12 where 100% of targets are defined, but the metric reads as 67%. Same for Jordan, which has 3 programs, none of which are at 100% targets defined, but has a metric reading of 33%.

**Comment by camgnostic** [comment] 2018-12-06 00:51
that is a great catch - it is totally counting indicators, not programs.  I'm working on that and should have a fix up first thing tomorrow

**Comment by hannalcamp** [comment] 2018-12-07 21:54
Mostly seeing everything correct, first potential errors I've found are in the Kenya country page. Only one program has any indicators, results, or evidence, but the metrics at the country level don't match those for that program, and I can't figure out the source of the discrepancy.

![screen shot 2018-12-07 at 2 36 09 pm](https://user-images.githubusercontent.com/38020496/49674000-a6942880-fa2d-11e8-941a-a3d3b5258a14.png)
![screen shot 2018-12-07 at 2 36 15 pm](https://user-images.githubusercontent.com/38020496/49674002-a6942880-fa2d-11e8-933d-04404d715ad0.png)

**Comment by camgnostic** [comment] 2018-12-08 01:48
So this appears to be due to the fact that there are funded programs with indicators assigned whose dates aren't set so they aren't showing in the program page, but there was no business logic not to count them for "whether an indicator has results".  
- Program 483 (Youth Empowered For Success (YES!) - Kenya) has 42 indicators, of which 42 have no targets but 2 have results.
- Program 502 (Kenya Election Violence Prevention and Response Program)has 39 indicators, 36 have no targets but 4 have results.
- Program 503 (Girls Improving Resilience with Livestock) has 12 indicators, 9 with no targets, 5 have results.

So the math the system is drawing from isn't just the one you see, but three that are masked by "you need to set your reporting dates" dialogs.  The true count is:
148 indicators for Kenya programs (including the 55 for the visible program and 93 that are masked by reporting date dialogs) of which 23 have results (of which 11 are masked by reporting date dialogs) which is 16% - home page is displaying accurate information.

@jennyhavah  - if we want to change behavior of queries this is a feature request, not a bug or failed QA item.  Let me know how you want to proceed here.

**Comment by jennyhavah** [comment] 2018-12-08 03:57
Good catch, @hannalcamp!

These programs that have results but no start/end dates were created during the pre-Winterhawks era -- before we introduced the concept of reporting periods. So that's why it's possible to have these "invisible results" that contribute to the chart metrics. Entering program start/end dates is a requirement for the system to be able to auto-generate target periods when you select a target frequency, which is why we deliberately obscure the existing indicators and results and ask you to first define your reporting period. Once you do that, you're in business.

For new programs, it's not possible to add indicators before you establish your reporting period.

So the system is behaving as expected, and I don't see any need to introduce new logic to handle this edge case. If anything, the "weird chart results" might serve the purpose of prompting them to do the thing we want them to do, which is to fix their reporting start/end dates for those programs.

So if everything else checks out, we can mark this Done.

**Comment by hannalcamp** [comment] 2018-12-10 02:57
Sounds good, I'm marking this as done.

**Closed** 2018-12-12 17:49 UTC
Labels: LOE - L
