### ISSUE TITLE
What to say to a user who successfully logs in, but is not assigned to any countries or programs

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#1482] opened 2019-04-24 21:25 UTC
This is an extension of #1341 -- a scenario we overlooked.

**Affects:**
People who have Tola user accounts and can successfully log in, but who are not assigned to any programs, and who do not have access (direct via Accessible Countries or indirect via Programs) to any Country pages.

# Acceptance criteria

- [ ] 1. I am taken to the page similar to the one described in Scenario 2 of #1341. It says:

**No available countries**
You do not have permission to view any countries. 

and/or

**No available programs**
You do not have permission to view any programs. 

followed by (ideally a single time, not repeated twice on one page)

You can request permission from your TolaData administrator. You can also reach the TolaData team by using the feedback form.

The phrase "feedback form" should be linked to https://docs.google.com/forms/d/e/1FAIpQLSclm2PAT9TJ9q23TT6YWQg6hj3EndUAdyF5k6kvNJHu6njNtw/viewform

- [ ] 2. I am taken to that page when I have no access to programs or countries, regardless of whether I am:

     - [ ] 2.1. A user logging in via Gmail.

     - [ ] 2.2. A user logging in with Django usernames and passwords.

     - [ ] 2.3. A user logging in via Mercy Corps emails (definitely an edge case, but possible)

## Housekeeping
* [ ]  Unit test/s written wherever applicable
* [ ]  i18n tags included wherever applicable
* [ ]  Functionality is accessible to people using screen readers

**Comment by axoplasm** [comment] 2019-04-25 17:04
Because there are two separate conditions here (country access and program access), it might be easier to have a custom message in the case of either no active countries or no active programs. For example:

User with access to no countries or programs:

![image](https://user-images.githubusercontent.com/169060/56754090-f9eae700-6740-11e9-9c6a-fb8f3d7e1f08.png)

User with access to an inactive program has implicit access to a country but not to any programs:

![image](https://user-images.githubusercontent.com/169060/56754148-27379500-6741-11e9-95d1-defae1028a3e.png)

**Comment by jennyhavah** [comment] 2019-04-25 17:31
@axoplasm I updated the original ticket with some suggested language, and added a link to the feedback form, which I'd left out.

**Comment by axoplasm** [comment] 2019-04-25 17:34
This is more complex than I thought. The conditions we can (trivially) test for are (paraphrasing)

### “User has an active country” 

“Active” in this context means “is the country that I should show for the user’s homepage.” A user with access to no countries implicitly has no active country.

There is an extreme edge here where a user with access to some country nonetheless has no “active” country for the purposes of choosing a homepage. I doubt anyone will encounter this edge. So the most likely scenario is that the user has access to __no__ programs

### “Active country has active programs”

“Active” in this context means “programs in the given country that have status: active.”

This is a common case for countries with no active programs. So we can't put a “you don't have access” message on this condition, or imply that the user is in any way responsible for the fact that we can't draw a list of programs. Sticking with “no active programs” is probably the most accurate description of this state.

**Comment by axoplasm** [comment] 2019-04-25 17:58
Here’s where we landed on this. We test the entire homepage on the condition of “User has an active country.” We’ll disregard the extreme edge mentioned above. If I don’t have an active country, I see:

![image](https://user-images.githubusercontent.com/169060/56757444-112dd280-6749-11e9-9abe-bd197d9c3c6d.png)

> You do not have permission to view any programs. You can request permission from your TolaData administrator.
>
> You can also reach the TolaData team by using the feedback form.

**Comment by RickieT** [comment] 2019-04-25 20:52
### **QA - Verified**
* Confirmed, here is the page with no country/program access:
![Screen Shot 2019-04-25 at 1 42 10 PM](https://user-images.githubusercontent.com/23220180/56767757-6b3a9200-6761-11e9-8725-ece3e8a70801.png)

**Closed** 2019-05-02 15:59 UTC
Labels: Deploy Ready Verified, UI details
