### ISSUE TITLE
Indicator setup > LoP only and Event target frequencies: Warning message showing before I have a chance to enter a value

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#2229] opened 2020-02-19 22:10 UTC
This is only on QA, not on Prod. To reproduce:

1. Add a new indicator
2. Go to Target tab and select "LoP-only" for target frequency.

Unexpected behavior: I get a warning to complete a field before I've had a chance to type anything.

![image](https://user-images.githubusercontent.com/33670923/74880844-00c29600-5321-11ea-98b9-131eb1f350c9.png)

This also happens for Event targets. In this case there's no warning message but the first event name is highlighted in red.

![image](https://user-images.githubusercontent.com/33670923/74881038-6b73d180-5321-11ea-982f-797b1620719c.png)

It does not happen for Midline/Endline or time-aware target frequencies.

**Comment by camgnostic** [comment] 2020-02-19 22:59
This is a regression caused by work on #2210  - the lop target errors were being cleared out by the _computed_ lop target errors.  Re-ordered the checks to make the tests less aggressive.

**Comment by camgnostic** [comment] 2020-02-19 23:04
Event target aggro validation was caused by a mistaken update to fix #2210  - event targets were not being tested for empty fields.  The test added for empty fields did not take initial create form status into account.  Fixed with PR #2230

**Comment by jennyhavah** [comment] 2020-02-20 01:24
Fixed. No longer seeing warnings when I select LoP-only or Event target frequency, prior to entering anything.

**Closed** 2020-05-18 22:46 UTC
Labels: bug
