### ISSUE TITLE
"Update actual value" function not working

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#2157] opened 2020-01-28 22:21 UTC
**Affects:** Result form Actual value field.

Potentially relevant or irrelevant:
1. I've got language set to French.
2. I'm entering values between zero and one.

# Issue

When I click "Update actual value", the old value cleared out but it was not updated with the current value.

![image](https://user-images.githubusercontent.com/33670923/73310581-6b2c5e80-41d9-11ea-8d4d-daaa5ccc401e.png)

**Comment by camgnostic** [comment] 2020-01-31 18:37
Regression due largely to the ambiguous disposition of #2125 - fixed in this iteration but should be revisited when #2125 is resolved

**Comment by jennyhavah** [comment] 2020-02-26 00:39
@camgnostic Found an edge case:

1. Find or create a saved indicator that doesn't have values for at least one disaggregation.
2. Enter some disaggregated values that do NOT add up to the total.
3. Submit. You'll see the warning with button to update actual value.
4. Hit "Reset". 

Here's what I'm seeing:

1. As expected, it empties out the disaggregated values you just added. 

2. But the "correction" in the sum row remains. My expectation is that the message would go away, as no longer relevant.

2. If I try to submit again, the "correction" stays there, plus I get a "One or more fields needs attention" warnings at the top... I would not expect this message to appear, since disaggregated values are not required fields...

**Comment by camgnostic** [comment] 2020-03-05 19:08
@jennyhavah  I've addressed the behavior in the above comment but found another bug with medium LOE and wanted to see if it was a release blocker or a nice to have:
1. Open a result that has disaggregated values OR actual value that is a truncated decimal (like 0.1 or 4.7 - the final zero is removed)
2. Hit "reset"
3. Notice that the trailing zeros have returned.

This is due to how HTML handles form resets, and while it's fixable it's medium LOE so I wanted to get a priority for this behavior (or find out if it's a bug at all in your eyes)

**Comment by camgnostic** [comment] 2020-03-05 19:39
Above comment broken out and moved to #2256

**Comment by jennyhavah** [comment] 2020-03-06 19:35
@camgnostic Moved back to Failed until the update is merged. Will retest once it's available on QA.

**Comment by jennyhavah** [comment] 2020-03-07 05:05
Edge case fixed. Reset clears the form and warning / "reconcile these numbers" functions as expected.

**Closed** 2020-05-18 22:46 UTC
Labels: bug
