### ISSUE TITLE
[Tracking] Indicator Help link is still directing to the old form 

### ISSUE THREAD

**Issue by RickieT** [mercycorps/TolaActivity#1300] opened 2019-03-25 16:23 UTC
As originally documented:
https://github.com/mercycorps/TolaActivity/issues/1038

It looks like this needs to be handled based on the comments in the ticket outside of the development team. This ticket is to track the escalation and eventual correction of the intended help link on indicator forms.

**Comment by jennyhavah** [comment] 2019-06-21 17:11
@sanjuroj Any idea if this got fixed? Can we close it?

**Comment by sanjuroj** [comment] 2019-06-21 17:26
Oh jeez, I'm not sure.  I know one of the problems was something one of the devs (maybe me?) had to update and others were ones that were stored in the DB, which Emily and LJ worked on.

**Comment by jennyhavah** [comment] 2019-06-21 18:07
Just went back to #1038 and reproduced the steps... Looks like it's linking to TolaWiki now. Yay!

**Closed by jennyhavah** 2019-06-21 18:07 UTC
