### ISSUE TITLE
Browse documents: Change default sort and enable manual sorting

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#805] opened 2018-11-19 20:00 UTC
# Stories
1. When I need to quickly access a document I recently added, I can easily find it because the Documents list is automatically sorted with the most recently added documents at the top.
2. Conversely, if I know a program document is one of the first ones I ever added, I can quickly find it by reverse sorting.

# Acceptance criteria

## Default sorting of documents
- [x] Documents are automatically sorted by _date added_, in reverse chronological order. I.e. the most recently added document is first.
- [x] Regardless of any manual sorting I may do, the next time I visit Browse > Documents, the default sort order is restored.

## Manual sorting by Date added
- [x] The _Date added_ column can be manually sorted chronologically in either direction.
- [x] It's visually obvious that those two columns are manually sortable.
- [x] It's visually obvious what the current primary sort is, and in which direction. (A common technique is to display up and down carets next to the column name, like these:  
![image](https://user-images.githubusercontent.com/33670923/48803095-dcaf7980-ecc5-11e8-9695-e5b3a55b0bbc.png)

## Manual sorting by Document name
- [x] The _Document_ column can be manually sorted in alphanumeric order, in either direction.

**Testing:**
- [x] IF results provide enough to paginate, ensure Pagination functions properly.
- [x] Manual sort function works for all columns
- [x] Results properly reflect information being sorted
- [x] Multiple searches need to be completed to confirm functional implementation based on acceptance criteria. 

**Estimated Test Time w/ Acceptance:**  
2  hours

## Housekeeping
- [ ] Unit test/s written wherever applicable
- [ ] i18n tags included wherever applicable
- [ ] Functionality is accessible to people using screen readers

**Comment by RickieT** [comment] 2019-01-11 20:49
test comment

**Comment by RickieT** [comment] 2019-02-13 20:00
**Deployment Verification**

- [x] Confirmed “Ready for Deploy” status
- [x] Media Verifying: 
![screen shot 2019-02-13 at 11 57 43 am](https://user-images.githubusercontent.com/23220180/52739978-e8d66a80-2f86-11e9-94be-63fb51900098.png)

**Comment by esinn** [comment] 2019-02-14 04:00
There's a bit of weirdness with the manual sort by Document. When I click it once, I get the following which doesn't look right from that first document title COATE but when I clicked into the document it looks like maybe the user was using Russian. I dunno. 
![image](https://user-images.githubusercontent.com/13574772/52761728-75098180-2fc9-11e9-9601-070dbe3c1ee3.png)

But then when I click on the Document header again to sort the other direction there's also two weird docs that I wouldn't expect (row 1 and 2). 
![image](https://user-images.githubusercontent.com/13574772/52761765-9e2a1200-2fc9-11e9-848f-87a45c8e5cab.png)

And then, when I click on the document header multiple times, that document YDP appears multiple times. Each time I click on the document header, the doc YDP creates another duplicate. And for the record, I checked and confirmed there's only one doc with the name YDP.
![image](https://user-images.githubusercontent.com/13574772/52761684-307de600-2fc9-11e9-9ad9-27c0ca3c11ea.png)

**Comment by jennyhavah** [comment] 2019-02-14 04:14
As discussed with Emily and Sanjuro in Slack: This is not a release blocker, so moved this back into the backlog instead of Failed, to avoid confusion over what needs to be worked on right now.

**Comment by KennyMonster** [comment] 2019-02-14 19:53
The COAT thing is definitely using Unicode characters (Cyrillic?) even though they look like normal ASCII characters:

```
>>> u'СОАТЕ'
u'\u0421\u041e\u0410\u0422\u0415'
```

That row duplication thing is really wonky though...

**Comment by RickieT** [comment] 2019-02-15 17:51
**QA Verified**
- [x] Performed sorting on multiple programs, and didn't see any duplicates, or inconsistencies in the sorting. No longer can I reproduce the issue reported by @esinn.

**Comment by RickieT** [comment] 2019-02-25 17:18
**Pre-Deploy Check:**
- [ ] Non-regressed
- [ ] Feature/fix can be found in release branch in staging environment, functioning as expected. 


If above is checked, this feature/fix is DEPLOY READY.

**Comment by sanjuroj** [comment] 2019-02-27 01:07
Fixed in Hucklepatch

**Closed** 2019-02-27 01:08 UTC
Labels: Deploy Ready Verified, HasTP, ½
