### ISSUE TITLE
Automatically test error condition behavior: A result is unassigned because its "date collected" falls outside of the program period AND targets are time-aware

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#1085] opened 2019-01-16 06:02 UTC
When a result is unassigned because its "date collected" falls outside of the program period AND targets are time-aware, the following are true:

1. The result is displayed in the table underneath the target period rows.
2. Under the table, we display error message: This date falls outside the range of your target periods. Please select a date between [localized program start date] and [localized program end date].

**Note:** See #1083 for more context

![image](https://user-images.githubusercontent.com/33670923/51229217-6cf9eb80-1910-11e9-972e-4256126f7b91.png)

**Comment by KennyMonster** [comment] 2019-02-21 23:36
This is actually difficult to test now since the result date is validated on the form, but I did manage to hack a case where I was able to reproduce and confirm the error message works correctly.

**Comment by RickieT** [comment] 2019-02-22 00:06
Closing, and adding to my test cases - will alter to fit a reasonable outcome due to the recent changes @KennyMonster mentioned above

**Comment by KennyMonster** [comment] 2019-02-22 00:30
After talking to Jenny, this needs to be an automated test.

**Closed** 2019-03-05 22:28 UTC
Labels: write tests
