### ISSUE TITLE
Rebuild IPTT <table> for accurate row widths (i.e. column counts)

### ISSUE THREAD

**Issue by axoplasm** [mercycorps/TolaActivity#2141] opened 2020-01-23 21:34 UTC
IPTT has several mismatched row widths (i.e. column counts) that need to be investigated and rebuilt.

![image](https://user-images.githubusercontent.com/169060/73025844-2bcece00-3de5-11ea-8b2d-4f4af7b04052.png)

For example the Female 15-19 disaggregation is three columns too short, all the RF level title rows are 1 column too short, etc.

All the red lines in the screenshot above should form a grid & shouldn’t be ragged on the right edge. We could do any of the following:

1. add a placeholder column cell to "soak up" the remainder of unused columns, 
2. (this is better) render empty cells
3. add `colspans` to particular columns

At the moment this has the worst effect on the header rows & is most apparent in places where the table background (white) “bleeds through” missing columns in the header (light gray)

**Comment by jennyhavah** [comment] 2020-02-03 19:46
Looks fabulous!

**Comment by jennyhavah** [comment] 2020-02-07 17:50
Moving this one back to Failed because I noticed alignment issues in both types of table -- that I hadn't seen before. Here's what I'm seeing:

![image](https://user-images.githubusercontent.com/33670923/74052685-3f566900-498f-11ea-947a-7eefdcbdc9a0.png)

![image](https://user-images.githubusercontent.com/33670923/74052698-454c4a00-498f-11ea-9cbf-468b46d1c00e.png)

**Comment by axoplasm** [comment] 2020-02-07 18:12
per this note in #2110:

> In dealing with #2141 (rebuilding the IPTT `<table>`), it might make sense to move the Baseline column out of the LoP group. This will reduce the number of column groups where we have to maintain accurate column counts, and simplify development.

**Comment by jennyhavah** [comment] 2020-02-07 23:19
> In dealing with #2141 (rebuilding the IPTT table), it might make sense to move the Baseline column out of the LoP group. This will reduce the number of column groups where we have to maintain accurate column counts, and simplify development.

I have no issues with moving the Baseline column out of the LoP group that has background shading.

**Comment by axoplasm** [comment] 2020-02-13 21:39
I’m back into this right now, it would help to know under which circumstances you're seeing table funniness

**Comment by jennyhavah** [comment] 2020-02-13 22:12
Steps to reproduce on QA:

1. Go to Reports, Periodic targets vs. actuals, and select the "Communities in Haiti Access New Technologies for Early warning and Response (CHANTER)" program. Choose "LoP only" for target frequency and click "View report". Here's what I see:

![image](https://user-images.githubusercontent.com/33670923/74483039-797daa00-4e6a-11ea-91b1-96c86c84d59a.png)

2. Change target periods to Midline and endline. Here's what I see:

![image](https://user-images.githubusercontent.com/33670923/74483096-9619e200-4e6a-11ea-816e-efb9b5468818.png)

3. Change target periods to Annual and Quarterly. Here's what I see:

![image](https://user-images.githubusercontent.com/33670923/74483132-a6ca5800-4e6a-11ea-9f17-4cfa29166ed2.png)

![image](https://user-images.githubusercontent.com/33670923/74483161-b2b61a00-4e6a-11ea-8a88-73e2639f8e24.png)

4. Go back to the Report page and select the same program in the "Recent progress for all indicators" menu. Here's what I get:

![image](https://user-images.githubusercontent.com/33670923/74483241-eb55f380-4e6a-11ea-840a-fda81f322415.png)

**Comment by axoplasm** [comment] 2020-02-13 23:15
OK this is kooky! It happens on programs that can't be grouped by RF level

**Comment by jennyhavah** [comment] 2020-02-20 01:29
Replicated all the steps above that I described, with the "Communities in Haiti Access New Technologies for Early warning and Response (CHANTER)" program. Column alignments looking good! Also checked a program with a results framework (WIT) and alignments still look good there.

**Closed** 2020-05-18 22:46 UTC
Labels: LOE-High, bug
