### ISSUE TITLE
You can't see this / do this page / messages

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#1341] opened 2019-04-03 01:10 UTC
# Acceptance criteria

### ... and I attempt to _access a URL_ I am not allowed to access [standard request]

- [x] 1. I am redirected to the login page.
- [x] 2. If I successfully log in, and I am authorized to see the page, I am taken to the page.
- [x] 3. If I successfully log in, and I am NOT authorized to see the page, I am taken to the page described in Scenario 2 below.

Testing note: Redirection to the page you were previously trying to see is currently implemented for standard Django auth (username/password) but **not** for Okta or Gmail. (This may be implemented in the future, but not for this ticket.) For Okta/Gmail right now, you're redirected to the home page. 

### ... and I attempt to _perform actions_ I am not allowed to perform [AJAX request]

We redirect you to the login page.

- [x] ~1. We display a PNotify growler in the lower left corner of the page, with two buttons: _OK_ and _Cancel_. It looks something like this, according to the latest style I've seen from Paul:~

    ![image](https://user-images.githubusercontent.com/33670923/55755901-298db580-5a05-11e9-8b40-85e644631278.png)

- [x] ~2. The message reads:~
~Warning
You are not logged in.
Would you like to log in now?~

- [x] ~3. If I click _Cancel_ or the "X" button in the upper right corner, the PNotify closes and we do NOT redirect them anywhere.~

- [x] ~4. If I click _OK_, I am taken to the login page.~
     - [x] ~4.1. If I successfully log in, I am returned to the page I was previously on. Let's NOT attempt to perform the action again, though, because the person may have been away from their computer for some time and not remember what they were trying to do.~

Testing note: The same limit on post-login redirect as mention above applies here as well.

## Scenario 2: When I AM logged in and I attempt to _access a URL_ I am not allowed to access [standard request]

Let's take them to a page with the following message, where the bold text is in our page title style and the message is in our usual body font.

**You need permission to view this page**
You can request permission from your TolaData administrator. 

## When I AM logged in and I attempt to _perform actions_ I am not allowed to perform [AJAX request]

Let's show a red warning PNotify message:

**Sorry, you do not have permission to perform this action.**
You can request permission from your TolaData administrator. 

Example scenarios where we'd use this:
1. Submitting a form I am not allowed to modify
2. Clicking a forbidden action button such as "Add a thing" or "Delete a thing"
     2.1. Not sure if this matters, but in the case of deletion, we might need to consider the timing. Most -- but not all! -- destructive actions have some sort of confirmation prompt. Ideally we show the "Nuh uh" message _before_ the confirmation prompt. 

## Housekeeping
* [ ]  Unit test/s written wherever applicable
* [x]  i18n tags included wherever applicable
* [ ]  Functionality is accessible to people using screen readers

**Comment by RickieT** [comment] 2019-04-03 19:09
@camgnostic Just a heads up here, currently, when a user cannot perform an action, buttons are grayed out and or not clickable.

**Comment by jennyhavah** [comment] 2019-04-03 19:40
@RickieT I had the same thought... Cameron told me that this messaging is not _instead of_ the front end approach, which is correct. It is back end validation for the rare instance where the front end isn't doing what it's supposed to do, for whatever reason. Similar to how we added back end validation to the program period modal, so that if the date picker for whatever reason allows a user to enter a bad date, the back end still catches it.

**Comment by RickieT** [comment] 2019-04-03 20:13
@jennyhavah okay, makes sense. just wanted to be clear on the requirements on this ticket

**Comment by KennyMonster** [comment] 2019-04-09 19:13
@jennyhavah Regarding Scenario 1 - section 1, I got this working for "Login with username and password". It does *not* work with "Log in with Gmail". It *might* work with the Okta option, but I can't test that locally at the moment.

**Comment by jennyhavah** [comment] 2019-04-09 19:32
Thanks, @KennyMonster. If we need additional tickets to track the Gmail or Okta work, can you please file them?

**Comment by KennyMonster** [comment] 2019-04-09 19:41
@jennyhavah It may not actually be possible to redirect when logging in via Gmail. The "URL you were trying to access" is data that needs to be kept on hand all throughout the login process, such that it can finally be used once logged in. In the case of Gmail, I think it's thrown out (because Gmail isn't set up to care about it).

Okta appears to hold on to the data, but I don't know what happens after an Okta login succeeds at the moment.

**Comment by RickieT** [comment] 2019-04-09 19:43
@KennyMonster for testing the implementation of scenario one, is there anyway to manually terminate a session via the dev console in chrome, so that I could try to get the warning to pop?

**Comment by KennyMonster** [comment] 2019-04-09 19:45
@RickieT If you manually hit `/accounts/logout/`, in a different tab, it will kill your current session.

**Comment by jennyhavah** [comment] 2019-04-09 19:54
> It may not actually be possible to redirect when logging in via Gmail. The "URL you were trying to access" is data that needs to be kept on hand all throughout the login process, such that it can finally be used once logged in. In the case of Gmail, I think it's thrown out (because Gmail isn't set up to care about it).

Okta appears to hold on to the data, but I don't know what happens after an Okta login succeeds at the moment.

I can file a ticket for Okta to poke at it in the future.

@KennyMonster I _think_ Cameron just fixed this? From Slack: In the scenario where someone tries to log in with gmail using a mercycorps.org email address, we are going to send them straight to Okta (where they’re supposed to log in) instead of bouncing them back to the Tola login page.

Are we talking about the same thing?

**Comment by KennyMonster** [comment] 2019-04-09 20:28
I think we are talking about separate things. The case of a redirect after login is something like:

User goes to: /program/515/
User is not logged in so they are redirected to: /accounts/login
They choose 1 of 3 mechanisms to log in, and once they do, they are sent directly to: /program/515/

The thing Cameron just fixed is a redirect from Gmail to Okta based on their email, but regardless of what page they were ultimately trying to reach.

**Comment by KennyMonster** [comment] 2019-04-09 20:53
![Screen Shot 2019-04-09 at 1 51 55 PM](https://user-images.githubusercontent.com/1278224/55834429-c9634600-5ace-11e9-90d7-eca4155c09f3.png)

The PNotify message when you submit an AJAX requestand do not have permission.

**Comment by jennyhavah** [comment] 2019-04-09 20:59
@KennyMonster Sorry, I'm a little lost. Can you please quote the specific chunk of the original ticket you're talking about, and clarify what we've implemented so far, instead of that?

**Comment by RickieT** [comment] 2019-04-10 18:19
**QA - FAILED**
I logged in with mctest.high@gmail.com, used "/accounts/logout/" in another tab to end my session, and then attempted to edit an indicator, and was met with an infinite loading and mini login page?:
![image](https://user-images.githubusercontent.com/23220180/55903419-7054ea00-5b82-11e9-94b8-034c42544321.png)

**Comment by KennyMonster** [comment] 2019-04-10 19:43
@RickieT The case you found above should now be fixed. Good catch! It was breaking when the login page was being shoved into a modal (instead of the requested form). It will now just put a string into the modal, but the expected PNotify message should show up to allow the user to redirect to the login page.

**Comment by RickieT** [comment] 2019-04-10 22:27
@KennyMonster I'm still seeing this behavior

**Comment by RickieT** [comment] 2019-04-11 17:17
**QA - Failure and Notes**
**Scenario 1:**

**Requirement PASSED**:  I am redirected to the login page, after the pop up appears asking me to login if my session has expired and I attempt to make an edit or perform an action

**Requirement FAILED:** If I successfully log in, and I am authorized to see the page, I am taken to the page.  
_I was on a program page, and attempted to edit an indicator, after getting the login message I clicked okay to login, and then landed on the country home page._ 

**BUG (maybe?)**: _If I clicked cancel to login, I was not re-directed anywhere, however, the page remained grayed out with a you are not logged in message, however, if I reloaded the page, the login screen appeared. Not sure if this is the intended design_


@jennyhavah @KennyMonster (more so for Jenny) , for the remaining scenario where we tell the user that they cannot edit something or perform an action, how does this work from the pnotify and front end perspective, if for instance, a low user cannot even _see_ options to submit forms or edit fields that are grayed out. Basicly, if PA is functioning how was designed for limitations on what users can and cannot do such as modify indicators/submit results etc...How do I test the last scenario in this ticket? And when would this issue potentially occur? I can't foresee any circumstance this would occur, and I've even tried manipulating the css/html in the document to let me do so and was not able.

**Comment by KennyMonster** [comment] 2019-04-11 20:36
@RickieT 

> Requirement FAILED: If I successfully log in, and I am authorized to see the page, I am taken to the page.
> I was on a program page, and attempted to edit an indicator, after getting the login message I clicked okay to login, and then landed on the country home page.

When you logged in, did you use username/pw, gmail, or okta? It currently only redirects on username/pw and not gmail or okta as noted at the top of the ticket.

> BUG (maybe?): If I clicked cancel to login, I was not re-directed anywhere, however, the page remained grayed out with a you are not logged in message, however, if I reloaded the page, the login screen appeared. Not sure if this is the intended design

I would say it's half bug, half our system was just never designed to handle this use case, so a lot of code ends up in a wonky state in this case, and not much can be done without changing a lot of our existing system.

It may be worth discussing with @jennyhavah if we should just redirect the whole page to the login screen if an AJAX request fails.

> for the remaining scenario where we tell the user that they cannot edit something or perform an action, how does this work from the pnotify and front end perspective, if for instance, a low user cannot even see options to submit forms or edit fields that are grayed out.

For testing this, I granted myself "high" permission, loaded the page so the UI elements were visible, changed my permission to "low", then clicked the UI element that would otherwise allow me to do something that I don't have permission to do.

**Comment by RickieT** [comment] 2019-04-11 20:49
@KennyMonster Looks like I tried okta or gmail, since typing in my username and password seemed to re-direct just fine. 

I'll use your tip for last party, checking by moving access from high to low

**Comment by RickieT** [comment] 2019-04-11 20:52
**QA - FAILED**
* message just says "Permission denied", dialogue does not match the required message: "Sorry, you do not have permission to perform this action.
You can request permission from your TolaData administrator."
![image](https://user-images.githubusercontent.com/23220180/55992237-f34c7200-5c60-11e9-90ad-fddf08505f2e.png)

**Comment by KennyMonster** [comment] 2019-04-11 21:17
@RickieT It turns out this is only a problem on this one endpoint which you found. The wrong error notification is showing through a combination of global error handling disabled on this one requested (thanks to Mahmood) and an error handler written in this *one* place by Rodrick... it totally works everywhere else :)

Anyways this should be fixed now in this case as well.

**Comment by RickieT** [comment] 2019-04-11 21:27
**QA - PASSED**

* alright, kinks worked out, this looks good now :
![image](https://user-images.githubusercontent.com/23220180/55994202-f302a580-5c65-11e9-9d9d-92e387428f7d.png)

**Comment by jennyhavah** [comment] 2019-04-12 03:45
@RickieT @KennyMonster For some reason I did not see this thread until just now. I see several questions directed at me, but now the ticket is in Ready to Deploy, before I had a chance to respond. 

Is this something Ken and I chatted about in person, perhaps? Ken, would you be able to summarize/walk me through the decisions and tradeoffs made here? Either in Github or in person is fine, if it's easier to show me.

**Comment by RickieT** [comment] 2019-04-12 04:39
@jennyhavah I see something about Okta being split into another ticket, but as far as the requirements in the ticket here, there were some back and forth because of failures. The requirements for the scenarios listed in the requirements of this ticket have been met, that is why I moved it to ready for deploy. If there are design concerns then lets move this back into doing until its resolved.

**Comment by RickieT** [comment] 2019-04-12 15:57
@jennyhavah @KennyMonster I think this comment, you guys make a decision on if this should be resolved in another ticket, or in this one - if another ticket, move this back to QA - if more work is decided here, then lets keep it a part of this ticket. Sound good?

> BUG (maybe?): If I clicked cancel to login, I was not re-directed anywhere, however, the page remained grayed out with a you are not logged in message, however, if I reloaded the page, the login screen appeared. Not sure if this is the intended design
> 
> I would say it's half bug, half our system was just never designed to handle this use case, so a lot of code ends up in a wonky state in this case, and not much can be done without changing a lot of our existing system.
> 
> It may be worth discussing with @jennyhavah if we should just redirect the whole page to the login screen if an AJAX request fails.

**Comment by KennyMonster** [comment] 2019-04-12 16:17
> Ken, would you be able to summarize/walk me through the decisions and tradeoffs made here?

@jennyhavah I don't think any new design decisions were made beyond what we discussed in person on Wed, which are reflected in the updates made to the top level ticket.

Regarding Rickie's comment (quoting my comment) above, I was pondering if it would make sense to change the design such that a full page redirection to the login screen takes place, in the case of an AJAX request fails because you are logged out. This would be in lieu of a "Would you like to log in now?" dialog prompt. The reasons behind why this might be a good idea are easier explained in person where I can show the wonky state the UI can get into.

For now though, things have been implemented/tested as originally designed.

**Comment by jennyhavah** [comment] 2019-04-12 17:39
@RickieT Ken just walked me through his suggestion in the comment immediately above this one, and I agree with his suggestion. You'll see in the original ticket -- for the "Not logged in / perform action" section of Scenario 1, I've crossed everything out and replaced it with a redirect to the login page.

@KennyMonster is working on this. I think he may also have come across another weird but, but I'll let him explain it if it's still relevant.

**Comment by RickieT** [comment] 2019-04-12 17:45
@jennyhavah I like the re-direct better, and I think it eliminates any complications. I'll wait for this one and run through it again when it hits QA column.

**Comment by KennyMonster** [comment] 2019-04-12 18:37
Commit 5261fbeca3ab8b0e15237fdf95a6641abc06ab25 contains the updates to now redirect to the login page when attempting to perform an AJAX request while logged out.

**Comment by RickieT** [comment] 2019-04-12 19:39
** QA - PASSED ** 

Scenario 2: now sends you to the login page, the other actions have already been tested and covered, lets move this to deploy ready

**Closed** 2019-05-02 16:01 UTC
Labels: Deploy Ready Verified
