### ISSUE TITLE
Result form disaggregation: Decimal value edits not saving

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#2164] opened 2020-01-30 00:44 UTC
To reproduce the issue:

1. Open up a saved result that has disaggregated values.
2. Tack on a .05 to all disaggregations and the original (total) actual value.
3. Save changes.
4. Reopen result and take a look at the disaggregated values.

What I'm noticing is that the .05 is missing both in two places:

1. The disaggregated number fields where I added the .05
2. The Sum rows.

![image](https://user-images.githubusercontent.com/33670923/73410216-70aba680-42b6-11ea-83e3-acad7872697e.png)

Note: This behavior does not occur if I add a single decimal places like .5.

**Comment by camgnostic** [comment] 2020-01-31 19:36
@jennyhavah I am unable to reproduce, was this perhaps fixed by another ticket?  If you verify can you give more information (which indicator in which program on QA)? 

Thank you!

**Comment by jennyhavah** [comment] 2020-02-03 18:27
Fixed. My decimal edits are now preserved.

**Closed** 2020-05-18 22:46 UTC
Labels: bug, results
