### ISSUE TITLE
New country disappears, needs refresh to reappear

### ISSUE THREAD

**Issue by sanjuroj** [mercycorps/TolaActivity#1394] opened 2019-04-12 22:04 UTC
Steps to reproduce:

Create a new country
<img width="1280" alt="Screen Shot 2019-04-12 at 2 47 58 PM" src="https://user-images.githubusercontent.com/6685499/56068092-61149e80-5d32-11e9-8632-5b4b2a4a0c48.png">

After saving, the country appears at the top of the list as expected.  
<img width="1280" alt="Screen Shot 2019-04-12 at 2 48 06 PM" src="https://user-images.githubusercontent.com/6685499/56068107-7984b900-5d32-11e9-94c6-edfb886a6f03.png">

Click on the country to expand/edit it, and it disappears
<img width="1280" alt="Screen Shot 2019-04-12 at 2 48 12 PM" src="https://user-images.githubusercontent.com/6685499/56068125-86091180-5d32-11e9-81f3-cc23acc50c29.png">

Refresh the page and it reappears
<img width="1280" alt="Screen Shot 2019-04-12 at 2 48 21 PM" src="https://user-images.githubusercontent.com/6685499/56068133-8f927980-5d32-11e9-8b3e-f905b81fa634.png">

**Comment by jennyhavah** [comment] 2019-04-12 22:54
This sounds _really_ familiar, like something @camgnostic was working on. 

@RickieT I know we have other tickets out there tackling similar issues of reactivity, but I think they're all in Ready to Deploy. Can you let us know if this is a regression or a new thing that needs to be tackled?

And are there any other pages in the Admin where something similar could be happening?

**Comment by RickieT** [comment] 2019-04-12 23:29
@jennyhavah Yeah I thought we squashed this... No this was the program page I think - I think its a non blocker for release, because we can still search for it afterword, but it is annoying for sure.

**Comment by jennyhavah** [comment] 2019-04-13 00:15
Okay, I think I found them:
#1355 sounds like a similar issue with Organizations, already fixed.
#1379 sounds like a similar issue with Programs, already fixed.

This ticket covers Countries. @sanjuroj can you verify that it's the same issue, and would you mind looking to see if it's the same deal in the Users section?

**Comment by sanjuroj** [comment] 2019-04-13 00:51
This is a different issue than #1355 or #1379 (which were quite similar to each other).  Those were both related to the Status and History tab not updating.  This is about a new Country actually disappearing from the main list and reappearing on refresh.  

One possible clue is that for the other three Admin types, after creation the newly created item is left in an expanded state and the header row info is updated with the relevant data.  With countries, saving a new country collapses the country and clicking on it makes it disappear.  There's something quite different about how the store is being updated for countries than other admin areas.  

I did confirm that this doesn't happen for the other admin items.

**Comment by jennyhavah** [comment] 2019-04-13 01:01
Thanks for the clarification, @sanjuroj.

@hannalcamp, not being as familiar with the Admin UI, I'll defer to you on whether it's annoying/confusing enough to rise the level of a release-blocker. If yes, please move to the This Release column. If not, Deferred.

**Comment by sanjuroj** [comment] 2019-04-13 06:06
I think the current behavior will pretty confusing for users when creating a new Country, however, since this is probably not something that will be done soon and probably not by anyone other than the Tola team, it wouldn't be terrible to delay this fix.  But if postponed, it should probably be fixed soon after.  My $0.02.

**Comment by jennyhavah** [comment] 2019-04-13 18:50
@sanjuroj Any sense of how much effort it will take to fix? 20 minutes? An hour? Half a day? More?

**Comment by sanjuroj** [comment] 2019-04-14 15:14
Closer to an hour than a day.

**Comment by jennyhavah** [comment] 2019-04-15 16:48
Just chatted with Hanna in Slack and she said that if it's low effort, let's go ahead and fix it. Moving to This Release.

**Comment by RickieT** [comment] 2019-04-16 03:17
**QA - PASSED**
* After creating a country multiple times, I was unable to re-create this issue

**Closed** 2019-05-01 21:25 UTC
Labels: Deploy Ready Verified
