### ISSUE TITLE
Change log doesn't record or display tracked fields in certain circumstances

### ISSUE THREAD

**Issue by hannalcamp** [mercycorps/TolaActivity#1508] opened 2019-04-26 17:48 UTC
*Affects all change logs*

# Issue
As a High-level user, when editing an indicator with results, tracked fields should include the indicator name, unit of measure field and radio button choice, LoP target and direction of change, and baseline. If any change is made to these it is captured once "Save Changes" is clicked.

However, if I make changes to those tracked fields _in conjunction_ with making significant changes to the target frequency, changes to those fields do not show up in the log.

_**Example 1**_: Remove semi-annual targets (rationale prompted), then change every single tracked field and ALSO add Annual targets before clicking Save (rationale prompted). 
_Result_: The tracked fields do not display in the change log... except for a change from non-cumulative to cumulative.
![Screen Shot 2019-04-26 at 11 12 39 AM](https://user-images.githubusercontent.com/38020496/56825590-d98d5c00-6816-11e9-87b1-8e5f8cf52722.png)

_**Example 2**_: Change all tracked fields and ALSO remove Midline/Endline targets (rationale prompted), then add Annual targets before clicking Save (rationale prompted). 
_Result_: The tracked fields do not display in the change log... except for the change from non-cumulative to cumulative.
![Screen Shot 2019-04-26 at 11 20 23 AM](https://user-images.githubusercontent.com/38020496/56825688-1eb18e00-6817-11e9-9570-900c0d1ef0cf.png)

_**Example 3**_: Change all tracked fields AND set periodic target type from LoP to Annual. Click Save changes. Fill out the rationale prompt and click OK on the subsequent confirmation prompt. Then finish creating your Annual targets and click Save changes (rationale prompted). 
_Result_: First batch of changes and the rationale do not display at all in the change log.
![Screen Shot 2019-04-26 at 11 24 52 AM](https://user-images.githubusercontent.com/38020496/56826074-700e4d00-6818-11e9-9149-42ddcf74e230.png)
![Screen Shot 2019-04-26 at 11 25 46 AM](https://user-images.githubusercontent.com/38020496/56826075-700e4d00-6818-11e9-95b0-05418da57a2a.png)

_**Contrasting example**_: Make a bunch of changes AND remove Annual targets (rationale prompted), then set periodic target frequency to LoP and save (rationale prompted). 
_Result_: Tracked fields DO display, but only in the second save.
![Screen Shot 2019-04-26 at 11 23 35 AM](https://user-images.githubusercontent.com/38020496/56825803-8071f800-6817-11e9-8245-3f91b7bf8f0d.png)

_**Contrasting example 2:**_ Change all tracked fields, change LoP to Annual and click _Create targets_ instead of _Save changes._ Confirm OK. Complete target values and save again. Only changes to targets are displayed, not the changes I made to all other tracked fields.

![image](https://user-images.githubusercontent.com/33670923/56830323-e4e28680-681a-11e9-9d27-22638868affd.png)

# Acceptance criteria 

On a saved indicator with linked results, the following things are true

- [x] 1. If I first click "Remove all targets", then make changes to any of our tracked fields, and add new targets, all changes are displayed in the change log.

     - [x] 1.1. The above is true, regardless of whether I use the "Save changes" button or the "Create targets button to generate the new targets.

-  [x] 2. If I first make changes to any of our tracked fields and _then_ click "remove all targets" and _then_ add new targets, all changes are displayed in the change log.

     - [x] 2.1. The above is true, regardless of whether I use the "Save changes" button or the "Create targets button to generate the new targets. <P>

- [x] 3. **Regression watch:** Deleting _individual events_ is working well right now... I can delete one event and then make other changes, or make a bunch of changes and then delete one event... In either case, I'm prompted for rationales at appropriate times and all changes are displayed. This continues to be the case, whatever we end up doing with regards to "Remove all targets".

## Housekeeping (where applicable)
- [ ] Unit test/s written 
- [ ] i18n strings included
- [ ] Is accessible to people using screen readers

**Comment by hannalcamp** [comment] 2019-04-26 17:49
@jennyhavah I'd like you to take a look at this if you can, especially to validate my acceptance criteria.

**Comment by hannalcamp** [comment] 2019-04-26 19:34
Looks good to me - I'm deleting my AC version.

**Comment by KennyMonster** [comment] 2019-04-26 22:45
I pushed a workaround that fixes the core issue here where changes are not being logged when the "Create targets" button is pressed.

The issue is that "Create targets" doesn't just create empty target fields, but also saves the entire Indicator form as well. The server had a check to see if this was a "Create targets" save vs a "Save changes" save, and did not log changes on the former. I removed this check, causing changes to be logged (if they exist) on every form save, regardless of what initiated it.

Because the user is not prompted for a rationale, a hardcoded "N/A" string is used. This was chosen to avoid creating another string needed to be translated (as it's already in use).

For testing, going through all of Hanna's examples above should now result in the changed fields being logged sans rationale. Because the change is just removing a check, it should be low impact and not require much in the way of regression testing.

**Comment by hannalcamp** [comment] 2019-04-26 23:14
Going through Criteria 1, I'm trying to Create Targets (after having removed them) and the button grays out upon clicking and doesn't create any new fields. This happens for any target period type other than LoP only.

**Comment by jennyhavah** [comment] 2019-04-27 00:23
@hannalcamp Cameron just reported in Slack that he fixed this issue.

**Comment by jennyhavah** [comment] 2019-04-27 00:26
I updated the original ticket to remove the acceptance criteria that would have required that we somehow capture a user's rationale even when the change logging was happening by way of the "Create target" button. As Ken explained, we are hard coding an "N/A" rationale in that particular scenario.

**Comment by jennyhavah** [comment] 2019-04-28 02:41
@hannalcamp  Can you recall what steps you took that resulted in a change log with percentage and non-cumulative? I'm unable to reproduce that.

I DO see a pattern where if I switch from percentage to number AND toggle from non-cumulative to cumulative, only the % to # change is logged.

![image](https://user-images.githubusercontent.com/33670923/56857602-7c7fcc00-6924-11e9-86c2-fb707f8ccaf8.png)

**Comment by hannalcamp** [comment] 2019-04-29 17:19
@jennyhavah The steps I took are essentially:

1. Change the Unit of Measure from # to %, and change direction of change, then hit "Remove targets".
2. Enter a rationale and click OK.
3. Set the periodic target type bar to a value like Quarterly, and hit "Save Changes" (NOT Create Targets)
4. Fill in the new empty target fields and hit Save Changes.
5. Enter a rationale and click OK.

The change log output of the above steps looks like this. As you can see, where the change from # to % is recorded, "Is Cumulative" is also reported as going to False, which seems wrong.
![Screen Shot 2019-04-29 at 11 16 37 AM](https://user-images.githubusercontent.com/38020496/56914124-89113b00-6a70-11e9-91f7-09afe5d522cb.png)

**Comment by KennyMonster** [comment] 2019-04-29 17:21
The issue with that cumulative/non-cumulative is that the form is hardcoding a "non-cumulative"  if its not set in the form because the radio button is hidden in some cases like LoP target type.

I don't know what the historical reason for doing this was and I'm kind of afraid to change it at this point.

**Comment by jennyhavah** [comment] 2019-04-29 17:28
Yes, there's some complex logic around when it's hard-coded. As I recall, LoP-only was supposed to always be non-cumulative _except_ for percentage indicators that are always cumulative.

@hannalcamp I realize it's not good to have any situation where the wrong value is appearing in the change log. But as Ken has assessed this work as too high risk to address prior to release, are you comfortable deferring to Satsuma or potentially Poblano? The alternative, I think, would be to not track the field at all until we get everything squared away.

**Comment by hannalcamp** [comment] 2019-04-29 17:32
Yep, totally good to defer. The change log does always show the correct value in the end (once new target values are added), so it's not WRONG wrong, just temporarily wrong.

**Comment by jennyhavah** [comment] 2019-04-29 19:48
Note to @RickieT that I'm in the process of filing a new ticket that will cover the cumulative/non-cumulative issues. That work can be deferred.

**Comment by jennyhavah** [comment] 2019-04-29 23:10
@hannalcamp @KennyMonster Filed ticket #1524 to cover issues related to logging cumulative/non-cumulative in combination with other indicator properties.

@RickieT Moving this back into QA for final review, now that this work is split out. In particular -- if you haven't already -- I'd appreciate you putting some extra scrutiny on change logging that combines deleting individual events with other changes to tracked fields.  (See the section in the original ticket called "regression watch".)

**Comment by RickieT** [comment] 2019-04-30 19:56
### QA Passed:
* Aside from a split issue from cumulative/non, I followed the criteria and examples in the description to a T, and found that the changes logged as we expected

**Closed** 2019-05-01 21:25 UTC
Labels: Deploy Ready Verified, bug, critical
