### ISSUE TITLE
In User Admin, Admin Role column doesn't show yes for (some?) admins.

### ISSUE THREAD

**Issue by sanjuroj** [mercycorps/TolaActivity#1466] opened 2019-04-23 23:10 UTC
In User Admin, Admin Role column in user table doesn't show up as "Yes" when a user is an admin.

To recreate, go to an arbitrary user and make them an admin (either User or Basic) for a country and save.  The Admin User column doesn't display as "Yes", even upon refresh.  

Super admins have a Yes in the Admin Role column.

**Comment by jennyhavah** [comment] 2019-04-23 23:49
@RickieT Can you let us know if this is something that used to test okay and now doesn't?

I'm also wondering if the change itself is being saved? I.e. is it just a problem with the user table, or are changes being lost?

**Comment by RickieT** [comment] 2019-04-24 15:57
@jennyhavah investigating this now

**Comment by RickieT** [comment] 2019-04-24 16:11
I set user mctest.low@gmail.com to basic admin role, and it did not update the admin role column to YES. However, when logging in as the user, I did have admin permissions. I can't confirm that the column updated to YES as of recent. 

CHANGES ARE NOT LOST - column is failing to update. 
![image](https://user-images.githubusercontent.com/23220180/56675374-c476c880-6670-11e9-94b0-9cd9bdc5b24b.png)

**Comment by axoplasm** [comment] 2019-04-24 17:46
sooooo....it turns out this column only checks whether the user has “staff” status per the Django admin. This is not quite the same as superuser — all it means is that I *can* log into the Django admin:

![image](https://user-images.githubusercontent.com/169060/56681345-00fcf100-667e-11e9-9279-8609800b6ed8.png)

In other words, this column is largely unrelated to any of the ways we traditionally refer to “admins.” It doesn’t mean “this user has Basic Admin access to some program,” which is kind of what I expected. And neither does it mean ”this user is a Super Admin,” which is not what I expected but would still make sense. It literally means “this user can log into the Django admin console.”

**Comment by axoplasm** [comment] 2019-04-24 17:48
Question now is, what do we want this to show?

* User has Basic Admin access somewhere
* User is a Super Admin (we would know this already by the __SUPER ADMIN__ badge
* Nothing, this is bogus info, let's just kill it

**Comment by jennyhavah** [comment] 2019-04-24 17:52
I would be fine killing the column, because we have the Admin filter that lets people find out who does/does not have this role. @hannalcamp is that ok with you?

**Comment by axoplasm** [comment] 2019-04-24 18:55
Oh dang I removed this before @hannalcamp weighed in. Let me know if we want to do something different

**Comment by hannalcamp** [comment] 2019-04-24 19:52
@jennyhavah I'm fine killing the column.

**Comment by jennyhavah** [comment] 2019-04-24 20:02
Validated that the Admin role column is 🔥 

![image](https://user-images.githubusercontent.com/33670923/56689956-20514980-6691-11e9-8471-87ca8a7f9110.png)

Moving to QA in case @RickieT wants to take a look, but it's done from my standpoint.

**Comment by RickieT** [comment] 2019-04-24 20:10
**QA - Confirmed**
* Admin role gone 
![image](https://user-images.githubusercontent.com/23220180/56690464-5a6f1b00-6692-11e9-9c2d-92a66f0f3f51.png)

**Closed** 2019-05-02 15:59 UTC
Labels: Deploy Ready Verified, bug
