### ISSUE TITLE
Redirect for old program page URLs to new (no indicator ID or type ID) program page URL

### ISSUE THREAD

**Issue by camgnostic** [mercycorps/TolaActivity#1133] opened 2019-01-28 19:53 UTC

**Comment by RickieT** [comment] 2019-02-05 19:43
@camgnostic can you point me to where i can check this?

**Comment by RickieT** [comment] 2019-02-07 19:48
Looks like the re-direct works properly from the old URL's, moving to deploy ready

**Comment by RickieT** [comment] 2019-02-13 22:55
**Deployment Verification**
- [x] Confirmed “Ready for Deploy” status
- old "/0/0" url redirects to the new url appropriately

**Closed** 2019-02-14 21:06 UTC
Labels: Deploy Ready Verified
