### ISSUE TITLE
IPTT landing page > Most recent: No longer displaying "2" in Most Recent

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#1945] opened 2019-09-10 00:00 UTC
To reproduce on QA:

1. Go to IPTT landing page.

2. Run a Most Recent report on any program.

Expected: Most Recent automatically populates with 2, with data to match.

Observed: Don't see a "2" in "Most recent". Not sure what's happening with the data.

**Comment by camgnostic** [comment] 2019-09-10 00:10
This was a regression from another bugfix - most recent counter was 1 too low on the quickstart page because it was counting from 0, I made it count from 1, but didn't update the part of the code that sent you on to the report, so it sent it one too far forward (notice it wasn't just not showing the 2 in the Most Recent input, it also was showing you the wrong periods, i.e. September and October instead of August and September) - fixed one spot in the code, testing: if it works for one program then (at least as far as this bug is concerned) it works for all.

**Comment by jennyhavah** [comment] 2019-09-10 00:17
Passed -- it's now consistently showing Most recent 2 periods.

**Closed** 2019-09-10 19:14 UTC
Labels: bug
