### ISSUE TITLE
Result form: UI updates (reorganization, relabeling, styling)

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#808] opened 2018-11-20 02:17 UTC
This ticket aggregates a bunch of UI updates to the Results form.

![image](https://user-images.githubusercontent.com/33670923/50994797-0f117200-14d2-11e9-9fb8-58cb9a4bc4cb.png)

# Acceptance criteria

- [x] 1. **Change form title Results to Result**. This item overlaps with an item in Ghost Pepper ticket #840 -- just want to make sure it's done by the time we release Huckleberry.
- [x] 2. **Change "Date collected" to "Result date"**. We've received emphatic feedback from numerous end users that the phrase "Date collected" is confusing and often inaccurate. Marie suggested this alternative, with agreement from a couple other PaQ advisors.
- [x] 3. **Move disaggregations immediately underneath the value you're disaggregating.** The idea is to visually communicate that the disaggregated values roll up into the Actual value. I've illustrated the worst case scenario where there are both Standard and New (custom) disaggregations.
- [x] 4. **Show who is submitting the result, from what organization.** These fields depend on the Partner Access release and may or may not be ready by the time we release Huckleberry. I just wanted to figure out where they'll eventually go, in any case.
- [x] 5. **Updated evidence section.** _This ticket only covers layout -- Additional interaction and validation details are covered in tickets #153 and #179._ 
     - [x] 5.1. The section is visually set off as a contained unit within the Result form.
     - [x] 5.2. Under the "Evidence" header is the message: Link this result to a record or folder of records that serves as evidence.
     - [x] 5.3. The **Record name** field is a free form text field. It is _not_ a required field under any circumstances.
          - [x] 5.3.1. ~If this form field is left empty, the standard "Please complete this field." message appears near the field upon submit.~ **UNDO: No longer a required field**
          - [x] 5.3.2. If the field is filled out, this name is displayed in the Evidence column of the Collected Data Table.
          - [x] 5.3.3. If the field is NOT filled out, we display the link to file or folder (see below) in the Collected Data Table
     - [x] 5.4. The **Link to file or folder** field is a free form text field. It is required **_only if the record name field is filled in._** That is, you can submit a link without a name, but you cannot submit a name without a link.
          - [x] ~5.4.1. If this form field is left empty, the standard "Please complete this field." message appears near the field upon submit.~ **UPDATED:** If the record name is filled in but the "Link to file or folder" field is empty, then the standard "Please complete this field" message appears and the text field is outlined in red.
- [x] 6. **Copy Browse Google Drive feature from Documents:** We'd like to bring over this feature from the Document form.
![image](https://user-images.githubusercontent.com/33670923/50930218-3e61a980-1414-11e9-9b95-36405ef4fd8a.png)
     - [x] 6.1. Instead of replicating the "Gdrive" button we use on the Document form, we'd like a plain text link right-aligned below the field, "Browse Google Drive". (We received usability feedback from the field that people were confused by the positioning and labeling of the original button, thinking that this was the _only_ type of file you could add.)
     - [x] 6.1. Link pops open the same Browse experience from the Document form, that behaves as expected
![image](https://user-images.githubusercontent.com/33670923/50991575-d2417d00-14c9-11e9-98a9-bf9923d6cc03.png)
     - [x] 6.2. When you select a file, the _Record name_ and _Link to file or folder_ form fields are filled in as expected.
7. "View" button functionality is covered in ticket #816.

## Housekeeping
- [ ] Unit test/s written wherever applicable
- [ ] i18n tags included wherever applicable

**Testing:** 
- [ ] Due to the incredible detail of each acceptance criteria broken down, testing will largely consist here of making sure acceptance criteria is met for design, and original function of the form remains unchanged. 
- [ ] Submit different types of files/urls to find any potential holes in application dealing with unsupported links or files
- [ ] Confirm communication with database, properly stored values & tables
- [ ] Functionality is accessible to people using screen readers

**Risks:**
Potential scope changes

**Estimated Test Time:**
2 - 4 hours

**Comment by camgnostic** [comment] 2018-12-19 21:40
Note: (per @jennyhavah ) the Remarks/Comments field will remain in the new form even though it is not in the mockup

**Comment by camgnostic** [comment] 2018-12-31 23:30
This ticket is in branch 808-results-form-styling

**Comment by camgnostic** [comment] 2018-12-31 23:46
@axoplasm  - heads up this needs some styling work, I'm still working on validation

**Comment by jennyhavah** [comment] 2019-01-09 21:52
@camgnostic I made some updates to this ticket to reflect the fact that we are no longer using Documents as linked evidence:
1. Removed the description field.
2. "Record name" is no longer a required field, so we need to remove the asterisk and validation of this field upon submit.
     2.1. 1/9/2019 note: Even though we are no longer going to have the "record" be a database object that you link to, the word "record" remains the preferred M&E term for the thing you want to link as evidence. This is why I continue to use it in form field labels and instructions.
2. I removed the _Browse TolaData records_ link and moved the _Browse Google Drive_ link to right align with the text field above.

**Comment by jennyhavah** [comment] 2019-01-10 20:13
@camgnostic @RickieT Just added two new details I'd forgotten to specify, FYI:

![image](https://user-images.githubusercontent.com/33670923/50994398-0b312000-14d1-11e9-885c-273a14f4e0d8.png)

**Comment by KennyMonster** [comment] 2019-01-28 18:09
@axoplasm The functionality for everything is done and merged into `huckleberry`, but it could use some styling love. My use of bootstrap columns for the form field + button is particularly bad here...

**Comment by axoplasm** [comment] 2019-01-28 19:47
Added some styling in commit 8f85fb4

**Comment by jennyhavah** [comment] 2019-02-01 05:02
CAVEAT: I may not be seeing all of Paul's styling updates. 

@axoplasm please check out number 5 in particular, because it's about the order of form fields and something I forgot to call out in the original ticket. The rest may or may not be relevant anymore.

Here's what I'm seeing at the moment:

![image](https://user-images.githubusercontent.com/33670923/52103037-8b800800-25db-11e9-9340-4e310765e7b7.png)

1. Vertical spacing issues between form fields and sections of form fields -- what belongs to what especially around the disaggregations area

2. "New disaggregations" has a different style than Standard.

3. Text and form fields come right up to the edge of the white background -- needs padding. 

4. I'd like to see the Evidence section set off more and highlighted as a contained unit _within_ the result, rather than another block of form fields. (See mockup -- not the styling particulars, but the general notion that the evidence is a key supporting element _within_ the result, rather than _after_ the result)

4. Can "Submitted by" be plain text like a note, rather than a form field?

5. The Project form field should be above "Submitted by" -- the Submitted by should be the last thing before Evidence.

**Comment by RickieT** [comment] 2019-02-01 05:17
@jennyhavah Hey jenny, i saw this too, but you shouldn't see this on qa server, try hard refreshing if you see it there, I also created a ticket for the different styling on new/standard disaggregations, as that is something that exists in production as well, i tossed it in ghost pepper

**Comment by RickieT** [comment] 2019-02-01 16:39
@jennyhavah you're right - I believe there are some styling fixes that are being missed here in the hb branch - ill folow up with @axoplasm

**Comment by RickieT** [comment] 2019-02-01 17:53
@axoplasm I've moved this into failed QA for now, assuming this was merged and deployed to the qa server within the past 2 days, its not showing there.

**Comment by axoplasm** [comment] 2019-02-01 17:55
Good call. It's either a regression or on a stale branch.

**Comment by RickieT** [comment] 2019-02-01 18:44
@axoplasm I may have prematurely moved it to ready  since after ken tossed it to your for styling you had added some stuff from what it looks from an older comment.

**Comment by axoplasm** [comment] 2019-02-01 18:57
I have thumbs in so many pies right now that I can't keep track of what I've worked on until looking directly at the code. It's possible I OKed this as ready thinking I had done it already.

**Comment by axoplasm** [comment] 2019-02-01 19:38
OK so turns out I did work in it but have kind of lost the thread. I'll get back to the feedback above

**Comment by axoplasm** [comment] 2019-02-01 20:39
Here's where we're at RN on my local (at commit 5877055):

![result-modal-ps](https://user-images.githubusercontent.com/169060/52148355-43360980-261e-11e9-8f1f-3c1c911dae23.png)

@jennyhavah I’m not sure about this:

> 5. Can "Submitted by" be plain text like a note, rather than a form field?

That field is pre-populated with the current user. There's an extension for "on behalf of" which I assume is coming with Partner Access?

**Comment by jennyhavah** [comment] 2019-02-13 00:39
@axoplasm Yes, "Submitted on behalf of" is part of Partner Access, as the menu is populated with Organizations.

Not sure if I'm answering the question, but I mocked up "Submitted by" as plain text instead of a non-editable form field, since it's not something the user can _ever_ edit, and on the general principle of not drawing boxes around things that don't need boxes.

**Comment by axoplasm** [comment] 2019-02-13 01:07
Aha I misunderstood "plain text" as "plain textfield." You mean you'd prefer to show it as just text (not a form element).

I get it now!

**Comment by RickieT** [comment] 2019-02-13 22:32
**Deployment Verification**

- [x] Confirmed “Ready for Deploy” status
- [x] Media Verifying: 
![screen shot 2019-02-13 at 2 31 51 pm](https://user-images.githubusercontent.com/23220180/52748727-1ed21980-2f9c-11e9-8ca9-eef17862e27c.png)

**Closed** 2019-02-14 21:05 UTC
Labels: 3, Deploy Ready Verified, HasTP, must have
