### ISSUE TITLE
Indicators are loading with all, one, or none on program pages that definitley have indicators

### ISSUE THREAD

**Issue by RickieT** [mercycorps/TolaActivity#1067] opened 2019-01-15 17:40 UTC
When a program page is loaded, indicators are sometimes not loading at all, or a little bit. This seems to be related across all indicator queries in production.

**Comment by sanjuroj** [comment] 2019-01-15 21:12
The problem was with indicator being set as a class variable in the Program page view.  Once you've called the page with an indicator specified, that same indicator will always be used in filters for the program.  The alternating happens because there are two processes assigned to apache to handle requests.

To reproduce:
navigate to /program/572/5835/0/
navigate back to /program/572/0/0
If you now refresh multiple times, sometimes you will see indicators, sometimes you won't. 
Navigating to any other program should result in alternating indicators and no indicators.

**Comment by RickieT** [comment] 2019-01-16 00:14
Verified fix is now live in production. Archiving...

**Closed** 2019-01-16 00:16 UTC
Labels: bug, critical
