### ISSUE TITLE
Indicator delete should redirect usefully and also require confirmation

### ISSUE THREAD

**Issue by camgnostic** [mercycorps/TolaActivity#1350] opened 2019-04-05 19:02 UTC
To reproduce:
click "add indicator"
give it a name
click "Save"
click "delete this indicator"
First issue: no confirmation message.
Second issue: success message disappears with redirect
Third issue: redirect goes to the update page you are already on (so it isn't really a redirect at all)
Fourth issue: the indicator _is_ deleted from the database, but the update page is showing you the indicator you were editing, so you are on a page in limbo that doesn't actually translate to a data object

Tagging @jennyhavah to clarify desired behavior

Note to dev: this is definitely a regression as this behavior was specified and QA'd elsewhere when indicator update and pNotify support were last overhauled, requires unit testing to prevent further regressions.

**Comment by jennyhavah** [comment] 2019-04-05 19:19
@camgnostic Before I respond, can you tell me what the behavior used to be, prior to regression, including any warning message language we used to use?

**Comment by jennyhavah** [comment] 2019-04-10 04:59
Glad you caught this, @camgnostic! I've included this scenario in a broader epic about deleting indicators. See #1370.

I am closing this ticket because the desired behavior is covered in the epic.

**Closed by jennyhavah** 2019-04-10 04:59 UTC
