### ISSUE TITLE
Adding a program results in weird UI behavior

### ISSUE THREAD

**Issue by camgnostic** [mercycorps/TolaActivity#1368] opened 2019-04-09 21:40 UTC
Admin->Programs
Add program
Fill out fields on first page
click "Save"
click on your newly created program, page goes blank, no info on page about what to do next

**Comment by jennyhavah** [comment] 2019-04-10 20:37
This sounds like it could be a potential release blocker -- certainly if actual program field data is not being saved and/or there's no way for the user to recover from the error.

@RickieT I'll leave it to you to investigate and fill us in on the details.

**Comment by RickieT** [comment] 2019-04-10 20:54
Let me take a look at this..

**Comment by RickieT** [comment] 2019-04-10 21:46
@camgnostic @jennyhavah We should probably fix this: 
I replicated this by following the steps above, only after I clicked saved, I clicked status and history, and the page was blank. 

Note that I have repeated this a couple of times, where this behavior was NOT seen, so its not 100% reproduceable

Heres what I saw and the errors in the console:
![image](https://user-images.githubusercontent.com/23220180/55915823-6ab9cd00-5b9f-11e9-95fd-93342bfafac2.png)

**Comment by jennyhavah** [comment] 2019-04-10 22:44
Thanks for the investigation, @RickieT. I'll go ahead and move the ticket into This Release. @KennyMonster or @camgnostic, could either of you assign this one to yourselves?

**Comment by KennyMonster** [comment] 2019-04-11 00:24
Also, the error handling for all network API calls done in the new admin is terrible, namely by not existing at all. This appears to be the root cause behind https://github.com/mercycorps/TolaActivity/issues/1368 and why it’s only sometimes reproducible. It becomes 100% reproducible if you turn off networking after you create a new program.

**Comment by RickieT** [comment] 2019-04-11 22:30
**QA - PASSED**
* Tried this numerous times and no longer able to produce the issue, moving to ready for deploy

**Closed** 2019-05-01 21:25 UTC
Labels: Deploy Ready Verified, bug
