### ISSUE TITLE
Program page indicator search: Unexpected behavior when accessing search toward the bottom of the screen

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#1129] opened 2019-01-28 13:07 UTC
I'm noticing some unexpected behavior with the indicator search bar. This is appearing on Production in addition to QA, so not a recent regression. 

Looking at a program page on my laptop. When the search bar is toward the lower part of the screen, the search bar and type-ahead list jump up above the drop-down element, like so.

![image](https://user-images.githubusercontent.com/33670923/51837906-b973fc80-22fc-11e9-9e31-68f0d90fc5e3.png)

Next, when I type into the search box, there is suddenly a big gap between the search area and the drop-down element, like so:

![image](https://user-images.githubusercontent.com/33670923/51837919-c264ce00-22fc-11e9-9517-38dffc655a62.png)

What I would expect and prefer is that the search box and type-ahead results would stay docked below the drop-down, and if I want to see more of it, I need to scroll.

**Comment by RickieT** [comment] 2019-02-07 19:24
I am unable to reproduce this issue in Huckleberry, search bar behavior appears to be normal. moving to ready for deploy.

**Comment by RickieT** [comment] 2019-02-13 22:57
**Deployment Verification**

- [x] Confirmed “Ready for Deploy” status
- [x] Media Verified: 
![screen shot 2019-02-13 at 2 57 07 pm](https://user-images.githubusercontent.com/23220180/52749964-ac633880-2f9f-11e9-9802-301480ca1310.png)
![screen shot 2019-02-13 at 2 56 39 pm](https://user-images.githubusercontent.com/23220180/52749965-acfbcf00-2f9f-11e9-99eb-cf659ad48abc.png)

**Closed** 2019-02-14 20:58 UTC
Labels: Deploy Ready Verified, UI details
