### ISSUE TITLE
Update front-end view and revise export of indicator plan

### ISSUE THREAD

**Issue by esinn** [mercycorps/TolaActivity#729] opened 2018-10-29 20:20 UTC
This ticket includes two main issues: 1) updating the front-end view of the indicator plan in the UI, and 2) improving the export of the indicator plan. 

Please see https://docs.google.com/document/d/17ercOPhESIV4-FJIfuPjYBRqjlXLQwD-ZYoifqkw0vw/edit for details on how our new export maps to current fields in Tola.

- [x] Update front-end view
The current front-end view of the indicator plan is missing a number of key fields from the indicator set-up model. It needs to be updated to include ~all~ most of the fields in the indicator set-up form, in the same order. 

- [x] Update export format
Currently, when you export an indicator plan for a program, it exports the data to a CSV file and the column headers are organized in no rhyme or reason (it's awful - see image below). Additionally, some of the field values are exported as the backend code (e.g. target frequency values include 1-6; is_cum values include 0-1; etc)
![image](https://user-images.githubusercontent.com/13574772/47677946-c65a4600-db7d-11e8-815c-5a70afd231ca.png)

Future state, the export of the indicator plan needs to be formatted (same as the IPTT export, with the program name at the top) and the columns organized to match the order of the fields in the indicator set-up model. Should be exported as XLSX as opposed to a CSV.

**Comment by jennyhavah** [comment] 2019-01-19 00:32
@esinn Some thoughts on this ticket.

Instead of copying the order of our indicator setup tabs and fields (that are idiosyncratic to TolaData), I'd like to see us get as closely as possible to the Mercy Corps Indicator Plan (IP) template. We should reorder our forms to model the IP template rather than the other way around. (The reordering would need to be a separate ticket.)

We also have fields in our indicator setup form that don't belong in the IP -- the most obvious example being periodic targets. I suggest leaving any field that is not in the MC template out of the IP template unless there's a compelling reason to include them. For example, a valid exception would be a column that USAID requires of most programs, that we already have in our forms.

If you like this approach, I think the first step is to do a mapping exercise where we look at our form fields and map them to the MC IP template. Sometimes the labels are a bit different, etc. We may even find a missing field that we need to add to our forms.

**Comment by jennyhavah** [comment] 2019-01-19 00:43
Here is the Mercy Corps template. @esinn I want to confirm that we should keep calling this the Indicator Plan. (The linked template calls it PMP.)

https://docs.google.com/spreadsheets/d/1HTQv4jXnB5sgWwSblEb94_amtwGjnWWFKT3Li8GimN4/edit?usp=sharing

**Comment by jennyhavah** [comment] 2019-01-28 19:46
Checked in with Emily, and she believes the correct term is "Indicator plan". She suggested vetting with our MEL advisors, so I just threw a question into Slack. Until we hear otherwise, let's go with "Indicator plan"

**Comment by KennyMonster** [comment] 2019-01-30 22:41
@jennyhavah Will this work for a XLS export?

[indicator_plan.xlsx](https://github.com/mercycorps/TolaActivity/files/2814798/indicator_plan.xlsx)

**Comment by KennyMonster** [comment] 2019-01-30 22:46
@axoplasm The indicator plan table has been updated to have all the correct data, but could probably use a bit of styling love. It currently looks like:

![screen shot 2019-01-30 at 2 46 17 pm](https://user-images.githubusercontent.com/1278224/52017994-db58b500-249d-11e9-8b08-f7cac780886a.png)

**Comment by jennyhavah** [comment] 2019-01-30 22:48
@KennyMonster it looks great! 

Request: Please change "Performance Monitoring Plan" to "Indicator plan".

**Comment by jennyhavah** [comment] 2019-01-30 22:48
Question, what are the green thingies? 
![image](https://user-images.githubusercontent.com/33670923/52017997-eda81280-24e0-11e9-8f31-899ec3afbf5d.png)

**Comment by jennyhavah** [comment] 2019-01-30 23:01
@esinn Take a look at the indicator export Ken linked above -- pretty great, right?! Couple of questions for you:

1) I notice that we're using a mix of sentence case and title case in the column headers.I've been advocating for sentence case throughout the application and am hoping we can keep it consistent both in the web and export versions. Is that okay with you?

2) I see that Ken went to some effort to style the export with colored background fills, bold headers, etc. I appreciate the aesthetics, but I actually was expecting something closer to the IPTT export -- no font styling, no fills, just plain text. People tend to be particular about customizing their reports, and won't necessarily want to use the Mercy Corps branding. Do you agree, or do you like the more stylized approach?

**Comment by KennyMonster** [comment] 2019-01-30 23:01
> what are the green thingies?

It's a highlight attention grabber from Excel. In this case it's because there is a warning associated with that cell. If you click it, it gives full warning text along with some options to "correct" it.

![screen shot 2019-01-30 at 2 58 55 pm](https://user-images.githubusercontent.com/1278224/52018548-a77e8f00-249f-11e9-8604-687ed96031f9.png)

In this case, it thinks "1.1" is a floating point number as the wrong type (a string), and wants to let you know if you apply operations to it that expect a float, it would probably break.

**Comment by jennyhavah** [comment] 2019-01-30 23:20
> In this case, it thinks "1.1" is a floating point number as the wrong type (a string), and wants to let you know if you apply operations to it that expect a float, it would probably break.

Hmm, I'm not quite following. Are the cells formatted more than they absolutely need to be, such that they are expecting certain types of inputs? Can we strip the export down more, so that the warnings don't appear? I'd like to avoid the export coming with a bunch of warnings that the user won't necessarily understand or know how to resolve. (I'll admit I don't know how I'd fix these, myself.)

**Comment by KennyMonster** [comment] 2019-01-31 00:04
I've googled around a bit and I can't seem to find a good way to get rid of the little green corners.

The problem isn't with formatting (fonts, borders, etc) but with the underlying data type of the value contained with in the cell. In this case, the value "1.1" is a string (think ASCII/Unicode encoding), as opposed to a literal binary representation of the number 1.1.

Excel sees the string that looks exactly like a number and thinks it's being helpful by pointing out that your "number" isn't actually a number, and problems might ensue if you treat it like one. In the case of the export though, it really is a string and not a number, and it wouldn't make sense to treat it like a number (e.g. what number is 3.2.1?)

This explains it a bit more:

https://support.office.com/en-us/article/fix-text-formatted-numbers-by-applying-a-number-format-6599c03a-954d-4d83-b78a-23af2c8845d0

**Comment by jennyhavah** [comment] 2019-01-31 19:49
Sounds good. So remaining tasks are:

1. Make all column headers sentence case
2. Change the tab name at the bottom of the table from PMP to "Indicator plan" (sentence case)

We can leave the styling as is.

We can punt on the green triangles issue. With Satsuma, that problem should go away as we'll be auto-generating the indicator numbers.

**Comment by axoplasm** [comment] 2019-01-31 19:57
I'm starting on the styling for this. One of the things I want to do is have a universal method for applying full-width and full-bleed styles to entire pages. This has a visual regression affecting the entire site. 

In particular, we will no longer have max-widths for the main body on non-mobile+non-desktop (i.e. tablet-sized) viewports:

#### Current:
![image](https://user-images.githubusercontent.com/169060/52081428-123ad380-254f-11e9-8d1b-bb8b782a7aa7.png)
(notice the ~100px or so of margin to the left and right of the program blob)

#### Proposed:
![image](https://user-images.githubusercontent.com/169060/52081488-33032900-254f-11e9-8f88-28d49e17cb32.png)
(margins replaced by the standard padding for the entire site

**Comment by RickieT** [comment] 2019-02-07 19:10
I believe the original criteria has been met based on my testing. A minor UI ticket was filed in regards to scaling on this page: #1156 

Moving to deploy ready

**Comment by jennyhavah** [comment] 2019-02-11 22:48
I'd like to see the button be consistent with our IPTT, with the label "Excel". "Export all" doesn't tell you the format to which you're exporting. It also implies that you can opt to partially export, which isn't the case.

**Comment by jennyhavah** [comment] 2019-02-11 22:51
I'm noticing inconsistency in that some columns appear to be truncating text while others spread across neighboring columns. An example:

![image](https://user-images.githubusercontent.com/33670923/52598956-24005e80-2e0c-11e9-9160-808f15745c17.png)

@KennyMonster what do you think about setting text to wrap instead of truncating or sprawling? Any risks, layout-wise? Could we get some wacky results if we do that?

**Comment by jennyhavah** [comment] 2019-02-12 18:29
After consulting with Rickie, I filed two new low-impact tickets -- 1161 and 1162 to address my two comments above.

**Closed** 2019-02-14 21:06 UTC
Labels: UI details
